**Student**: Michael McCann <br>
**Assignment**: Dates and Times (Core) <br>
**Date**: 26 JAN 2022

1) Import the numpy library

In [2]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [3]:
distance = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])
distance

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

In [4]:
type(distance)

numpy.ndarray

3) Use the min() and max() functions to find the minimum and maximum distances

In [5]:
print("min: " + str(min(distance)))
print("max: " + str(max(distance)))

min: 100
max: 10000


4) To find the average distance, use the np.mean() function

In [6]:
np.mean(distance)

2625.0

5) use the sum() function to find the total distance

In [7]:
sum(distance)

21000

6) Another valuable function is the cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [8]:
np.cumsum(distance)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [9]:
np.round(distance)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [10]:
time = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [11]:
speed = distance/time
speed

array([9.41619586, 9.37207123, 8.29015544, 7.0528079 , 6.41135237,
       5.92265019, 5.77253888, 5.69006231])

In [12]:
for i in range(7):
    print(f"The olympic record time for {distance[i]} meter race is {time[i]} seconds imputing a speed of {round(speed[i], 2)} m/s")

The olympic record time for 100 meter race is 10.62 seconds imputing a speed of 9.42 m/s
The olympic record time for 200 meter race is 21.34 seconds imputing a speed of 9.37 m/s
The olympic record time for 400 meter race is 48.25 seconds imputing a speed of 8.29 m/s
The olympic record time for 800 meter race is 113.43 seconds imputing a speed of 7.05 m/s
The olympic record time for 1500 meter race is 233.96 seconds imputing a speed of 6.41 m/s
The olympic record time for 3000 meter race is 506.53 seconds imputing a speed of 5.92 m/s
The olympic record time for 5000 meter race is 866.17 seconds imputing a speed of 5.77 m/s


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [13]:
 speed_mph = speed * .00062 * 3600
 speed_mph

cheetah = speed_mph >= 75.0
cheetah

array([21.01694915, 20.91846298, 18.50362694, 15.74186723, 14.31013849,
       13.21935522, 12.88430678, 12.70021907])

In [34]:
for i in range(7):
    if(cheetah[i] == False):
        print(f"The {distance[i]} meter olympic record holder ran at {round(speed_mph[i], 2)} but was NOT faster than a cheetah")
    else:
        print(f"The {distance[i]} meter olympic record holder ran at {speed_mph[i]} and WAS faster than a cheetah")

### I may have gone beyond the scope of the prompt with the below function....

The 100 meter olympic record holder ran at 21.02 but was NOT faster than a cheetah
The 200 meter olympic record holder ran at 20.92 but was NOT faster than a cheetah
The 400 meter olympic record holder ran at 18.5 but was NOT faster than a cheetah
The 800 meter olympic record holder ran at 15.74 but was NOT faster than a cheetah
The 1500 meter olympic record holder ran at 14.31 but was NOT faster than a cheetah
The 3000 meter olympic record holder ran at 13.22 but was NOT faster than a cheetah
The 5000 meter olympic record holder ran at 12.88 but was NOT faster than a cheetah


In [57]:
def fasterthan():
    while True:
        hubris = input("Do you think you can run faster than a cheetah? Please answer YES or No: ")
        if(hubris == "YES"):
            print("\nOh really??")
            howfast()
            return
        elif(hubris == "NO"):
            print("Good. You're smarter than you look.")
            return
        else:
            print("Please answer YES or NO!")

def howfast():
    your_dist = input("How far did you run (in meters)? Please enter numbers only: ")
    your_time = input(f"How long did it take you to run {your_dist}? Please enter numbers only: ")
    your_speed_ms = float(your_dist) / float(your_time)
    your_speed_mph = your_speed_ms * .00062 * 3600
    if (your_speed_mph >= 75.0):
        print(f"Wow! You ran {your_speed_mph} mph. You ARE faster than a cheetah!")
        print("\nThat is literally unbelievable...")        
        truth = input("Are you sure you're telling the truth? Please answer YES or NO: ")
        if truth == "YES":
            print("Okay... if you say so")
        elif(truth == "NO"):
            while True:
                print("\nThank you for your honesty")
                again = input("Would you like to rectify your mistake? Please answer YES or NO :")
                if again == "YES":
                    print("\nOkay, here we go...\n")
                    fasterthan()
                    break
                elif again == "NO":
                    print("Okay! See you later aligator!")
                    break
                else:
                    print("Please answer YES or NO")
    else:
        print(f"Sorry, You only ran {your_speed_mph} mph. You are NOT faster than a cheetah!")

fasterthan()

Do you think you can run faster than a cheetah? Please answer YES or No: YES

Oh really??
How far did you run (in meters)? Please enter numbers only: 1000
How long did it take you to run 1000? Please enter numbers only: 2
Wow! You ran 1116.0 mph. You ARE faster than a cheetah!

That is literally unbelievable...
Are you sure you are telling the truth? Please answer YES or NO: NO

Thank you for your honesty
Would you like to try again? Please answer YES or NO :YES

Okay, here we go...

Do you think you can run faster than a cheetah? Please answer YES or No: YES

Oh really??
How far did you run (in meters)? Please enter numbers only: 1000
How long did it take you to run 1000? Please enter numbers only: 234
Sorry, You only ran 9.538461538461538 mph. You are NOT faster than a cheetah!
